GoogleCloudPlatform/solution-acceleration-toolkit

- README.md
- go.mod
`$ go mod init github.com/GoogleCloudPlatform/healthcare-data-protection-suite`
> add go module

- CODEOWNERS
- build/go_check.sh
- build/presubmit.yaml
Fixes https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/10
> Add presubmit config.

- templates/tfengine/components/org/audit/main.tf
> Pin audit resources module version to minor.

- templates/tfengine/components/cicd/main.tf
Also enabled admin API. These are needed for a precondition
check from project factory module.
https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/modules/core_project_factory/scripts/preconditions/preconditions.py#L234
> Grant serviceusageViewer role to GCB SA in devops project.

- build/md_check.sh
Issue https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/33
> Pin markdownlint-cli to ver 0.22.0

- cmd/tfimport/main.go
- internal/runner/runner.go
- internal/tfimport/tfimport.go
- internal/tfimport/tfimport_test.go
Fixes https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/81
> Add dry run to importer

- templates/tfengine/components/cicd/manual/configs/terragrunt.sh
- templates/tfengine/components/cicd/manual/configs/tf-apply.yaml
- templates/tfengine/components/cicd/manual/configs/tf-deletion-check.sh
- templates/tfengine/components/cicd/manual/configs/tf-plan.yaml
> Suppress verbose terragrunt outputs.

- templates/tfengine/components/cicd/manual/configs/tf-apply.yaml
- templates/tfengine/components/cicd/manual/configs/tf-plan.yaml
- templates/tfengine/components/cicd/manual/configs/tf-validate.yaml
This will show up in the cloud build result page as step name.
> Add ID to cloud build steps.

- templates/tfengine/components/bootstrap/terraform.tfvars
- templates/tfengine/components/cicd/manual/configs/terragrunt.sh
- templates/tfengine/components/cicd/manual/configs/tf-apply.yaml
- templates/tfengine/components/cicd/manual/configs/tf-plan.yaml
- templates/tfengine/components/cicd/manual/configs/tf-validate.yaml
- templates/tfengine/components/org/audit/terraform.tfvars
- templates/tfengine/components/org/monitor/forseti/terraform.tfvars
> Streamline cloud build step ID.

- cmd/tfimport/README.md
- internal/tfimport/importer/google_service_networking_connection.go
- internal/tfimport/tfimport.go
The import ID is undocumented, but there's an example of someone using it here: https://github.com/terraform-providers/terraform-provider-google/issues/2705#issue-392292473
> Importer: Add google_service_networking_connection

- examples/tfengine/full.yaml
- internal/tfengine/schema.go
- templates/tfengine/recipes/folder/folder.yaml
- templates/tfengine/recipes/folder/project.yaml
- templates/tfengine/recipes/org/audit.yaml
- templates/tfengine/recipes/org/folder.yaml
- templates/tfengine/recipes/org/monitor.yaml
- templates/tfengine/recipes/org/project.yaml
> move project fields to PROJECT and remove project/folder prefixes

- build/go_check.sh
- go.mod
- go.sum
> add check to make sure go deps are up-to-date

- internal/tfimport/importer/resources_test.go
- internal/tfimport/importer/simple_importer.go
This also makes it respect the interactive flag.
> Fix SimpleImporter to match interface

- examples/policygen/config.yaml
- examples/tfengine/full.yaml
- examples/tfengine/simple.yaml
- go.mod
- go.sum
- internal/tfengine/schema.go
- templates/tfengine/components/cicd/README.md
- templates/tfengine/components/cicd/manual/README.md
- templates/tfengine/components/cicd/manual/main.tf
- templates/tfengine/components/cicd/manual/terraform.tfvars
- templates/tfengine/components/cicd/manual/variables.tf
Fixes https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/50
> support folder level cicd

- examples/tfengine/full.hcl
- examples/tfengine/simple.hcl
- internal/tfengine/config.go
- templates/tfengine/recipes/folder/folder.hcl
- templates/tfengine/recipes/folder/project.hcl
- templates/tfengine/recipes/org/audit.hcl
- templates/tfengine/recipes/org/base.hcl
- templates/tfengine/recipes/org/folder.hcl
- templates/tfengine/recipes/org/foundation.hcl
- templates/tfengine/recipes/org/monitor.hcl
- templates/tfengine/recipes/org/org_policies.hcl
- templates/tfengine/recipes/org/project.hcl
- templates/tfengine/recipes/project/resources.hcl
- templates/tfengine/recipes/terraform/terraform.hcl
> add label and rename templates to template

- examples/policygen/config.yaml
- examples/tfengine/full.hcl
- internal/policygen/config.go
- internal/policygen/policygen.go
- internal/policygen/policygen_test.go
- internal/policygen/schema.go
- templates/policygen/forseti/org/bigquery_allow_locations.yaml
- templates/policygen/forseti/org/dataproc_allow_locations.yaml
- templates/policygen/forseti/org/iam_allow_domains.yaml
- templates/policygen/forseti/org/iam_deny_public_access.yaml
- templates/policygen/forseti/org/iam_enable_audit_logs.yaml
- templates/policygen/forseti/org/network_enable_firewall_logs.yaml
- templates/policygen/forseti/org/network_enable_flow_logs.yaml
- templates/policygen/forseti/org/sql_allow_locations.yaml
- templates/policygen/forseti/org/sql_deny_public_access.yaml
- templates/policygen/forseti/org/storage_allow_locations.yaml
- templates/policygen/forseti/org/storage_allow_uniform_bucket_access_only.yaml
This supports sharing attributes between different types of policies.
Fixes #190
> improve policygen schema

- examples/policygen/config.yaml
- internal/policygen/config.go
- internal/policygen/policygen.go
- internal/policygen/schema.go
- internal/tfengine/schema.go
- templates/policygen/org_policies/main.tf
- templates/policygen/org_policies/variables.tf
- Also fix engine schema
Fixes #212
> policygen: improve schema and defaults

- go.mod
- go.sum
- internal/tfimport/importer/google_compute_network_peering.go
- internal/tfimport/tfimport.go
- internal/tfimport/tfimport_test.go
Adding these tests did actually catch a few bugs, so they're worth having, and they're really easy to add.
Fixes #207 
WANT_LGTM=all
> Importer: Add sanity tests and fix small bugs

- examples/tfengine/full.hcl
- templates/tfengine/components/terragrunt/leaf/main.tf
- templates/tfengine/recipes/project/resources.hcl
> support arbitrary config blocks and use random

- cmd/tfimport/main.go
- internal/tfimport/tfimport.go
- internal/tfimport/tfimport_test.go
Also add one missing resource, noticed while testing, and make InsufficientInfo errors trigger a retry.
> Refactor importer code into internal

- templates/tfengine/components/cicd/manual/README.md
- templates/tfengine/components/cicd/manual/main.tf
- templates/tfengine/components/cicd/manual/terraform.tfvars
- templates/tfengine/components/cicd/manual/variables.tf
Fixes https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/243
> add an individual control to disable deployment trigger

- build/go_check.sh
This is managed by Renovate Bot now. See https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/pull/267
WANT_LGTM=all
> Remove deps check from CI

- examples/policygen/config.yaml
- examples/policygen/generated/gcp_org_policies/main.tf
- examples/tfengine/full.hcl
- examples/tfengine/generated/full/live/org_policies/main.tf
- examples/tfengine/generated/simple/live/org_policies/main.tf
- internal/policygen/schema.go
- templates/policygen/org_policies/main.tf
> add disable SA creation and upload to default org policies

- internal/jsonschema/validate.go
- internal/policygen/load.go
- internal/tfengine/config.go
- internal/tfengine/schema.go
- internal/tfengine/tfengine.go
- templates/tfengine/recipes/org/org_policies.hcl
> support per-recipe schema

- build/presubmit.yaml
- examples/tfengine/generated/full/cicd/configs/tf-apply.yaml
- examples/tfengine/generated/full/cicd/configs/tf-plan.yaml
- examples/tfengine/generated/full/cicd/configs/tf-validate.yaml
- examples/tfengine/generated/simple/cicd/configs/tf-apply.yaml
- examples/tfengine/generated/simple/cicd/configs/tf-plan.yaml
- examples/tfengine/generated/simple/cicd/configs/tf-validate.yaml
- templates/tfengine/components/cicd/manual/configs/tf-apply.yaml
- templates/tfengine/components/cicd/manual/configs/tf-plan.yaml
- templates/tfengine/components/cicd/manual/configs/tf-validate.yaml
- Terragrunt is upgraded to 0.23.25
> update cicd container version

- examples/tfengine/generated/full/cicd/configs/tf-deletion-check.sh
- examples/tfengine/generated/simple/cicd/configs/tf-deletion-check.sh
- templates/tfengine/components/cicd/manual/configs/tf-deletion-check.sh
Ref: https://stedolan.github.io/jq/manual/
Error when no resource change is found:
jq: error (at <stdin>:1): Cannot iterate over null (null)
> do not error out when jq takes in a null object

- examples/tfengine/generated/full/live/monitor/forseti/main.tf
- examples/tfengine/generated/simple/live/monitor/forseti/main.tf
- templates/tfengine/components/org/monitor/forseti/main.tf
Reverts GoogleCloudPlatform/healthcare-data-protection-suite#306
There is issue with the latest forseti. Do not use this in the templates for now
> Revert "upgrade Forseti module version"

- templates/tfengine/components/bootstrap/main.tf
> allow lien to be false in bootstrap

- build/go_check.sh
- go.sum
- internal/tfengine/tfengine.go
- internal/tfimport/importer/google_billing_budget.go
- internal/tfimport/importer/google_resource_manager_lien.go
- scripts/check_importer_supports_engine/main.go
Inspired by https://github.com/github/super-linter. Super Linter itself produces too much output for our repo.
Also correct findings.
> Add golangci-lint to CI

- examples/policygen/generated/forseti_policies/overall/bigquery_allow_locations.yaml
- examples/policygen/generated/forseti_policies/overall/iam_allow_domains.yaml
- examples/policygen/generated/forseti_policies/overall/iam_deny_public_access.yaml
- examples/policygen/generated/forseti_policies/overall/sql_allow_locations.yaml
- examples/policygen/generated/forseti_policies/overall/storage_allow_locations.yaml
- scripts/package_policies.sh
- templates/policygen/forseti/overall/bigquery_allow_locations.yaml
- templates/policygen/forseti/overall/iam_allow_domains.yaml
- templates/policygen/forseti/overall/iam_deny_public_access.yaml
- templates/policygen/forseti/overall/sql_allow_locations.yaml
- templates/policygen/forseti/overall/storage_allow_locations.yaml
- fixed empty exemption list needs to be specified 
- more inclusive language
> bring in upstream fixes

- .gitattributes
See https://help.github.com/en/github/administering-a-repository/customizing-how-changed-files-appear-on-github
> Ignore generated files in diffs

- cmd/policygen/README.md
- cmd/policygen/main.go
- internal/policygen/load.go
- internal/policygen/policygen.go
- internal/policygen/policygen_test.go
- internal/policygen/testdata/org.tfstate
- internal/policygen/testdata/state
- internal/policygen/testdata/subfolder/project.tfstate
> policygen: support reading multiple state file from dir

- scripts/check_importer_supports_engine/main.go
They're not necessary and just clutter the output.
> Remove log messages from importer check script

- build/presubmit.yaml
Reference: https://cloud.google.com/cloud-build/docs/api/reference/rest/v1/projects.builds#machinetype
> Use higher-cpu machine to hopefully speed up CI

- examples/tfengine/devops.hcl
- examples/tfengine/generated/devops/bootstrap/README.md
- examples/tfengine/generated/devops/bootstrap/main.tf
- examples/tfengine/generated/devops/cicd/README.md
- examples/tfengine/generated/devops/cicd/configs/terragrunt.sh
- examples/tfengine/generated/devops/cicd/configs/tf-apply.yaml
- examples/tfengine/generated/devops/cicd/configs/tf-deletion-check.sh
- examples/tfengine/generated/devops/cicd/configs/tf-plan.yaml
- examples/tfengine/generated/devops/cicd/configs/tf-validate.yaml
- examples/tfengine/generated/devops/cicd/main.tf
- examples/tfengine/generated/devops/cicd/terraform.tfvars
- examples/tfengine/generated/devops/cicd/variables.tf
- examples/tfengine/generated/devops/live/README.md
- examples/tfengine/generated/devops/live/cicd/main.tf
- examples/tfengine/generated/devops/live/cicd/terraform.tfvars
- examples/tfengine/generated/devops/live/cicd/variables.tf
- examples/tfengine/generated/devops/live/terragrunt.hcl
> add a devops only example

- cmd/policygen/README.md
- cmd/policygen/main.go
- go.mod
- go.sum
- internal/licenseutil/licenseutil.go
- internal/policygen/load.go
- internal/policygen/policygen.go
- internal/policygen/policygen_test.go
- internal/terraform/state.go
- internal/terraform/state_test.go
Fixes #206 
TESTED=using our testing devops project
> policygen: support reading state files from gcs

- examples/tfengine/generated/folder_foundation/live/audit/resources/main.tf
- examples/tfengine/generated/folder_foundation/live/audit/resources/terraform.tfvars
- examples/tfengine/generated/org_foundation/live/audit/resources/main.tf
- examples/tfengine/generated/org_foundation/live/audit/resources/terraform.tfvars
- examples/tfengine/generated/org_foundation/live/org_policies/main.tf
- examples/tfengine/generated/team/live/example-prod-apps/project/terragrunt.hcl
- examples/tfengine/generated/team/live/example-prod-apps/resources/main.tf
- examples/tfengine/generated/team/live/example-prod-data/project/terragrunt.hcl
- examples/tfengine/generated/team/live/example-prod-data/resources/main.tf
- examples/tfengine/generated/team/live/example-prod-networks/resources/main.tf
- examples/tfengine/generated/team/live/example-prod-secrets/resources/main.tf
- internal/hcl/hcl.go
- internal/tfengine/tfengine.go
> format generated engine files

- examples/tfengine/folder_foundation.hcl
- examples/tfengine/generated/folder_foundation/live/prod/folder/main.tf
- examples/tfengine/generated/folder_foundation/live/prod/folder/outputs.tf
- examples/tfengine/generated/folder_foundation/live/prod/folder/terraform.tfvars
- examples/tfengine/generated/folder_foundation/live/prod/folder/terragrunt.hcl
- examples/tfengine/generated/folder_foundation/live/prod/folder/variables.tf
- examples/tfengine/generated/folder_foundation/live/prod/team1/folder/main.tf
- examples/tfengine/generated/folder_foundation/live/prod/team1/folder/outputs.tf
- examples/tfengine/generated/folder_foundation/live/prod/team1/folder/terraform.tfvars
- examples/tfengine/generated/folder_foundation/live/prod/team1/folder/terragrunt.hcl
- examples/tfengine/generated/folder_foundation/live/prod/team1/folder/variables.tf
> create some sub folders in folder_foundation

- examples/policygen/generated/gcp_org_policies/main.tf
- internal/hcl/hcl.go
- internal/policygen/policygen.go
- internal/tfengine/tfengine.go
also make fmt commands and output quiet
> policygen: format generated tf files

- templates/tfengine/recipes/devops.hcl
This makes it more obvious what is enabled and disabled.
> add more required fields in cicd block

- examples/tfengine/generated/folder_foundation/live/monitor/forseti/main.tf
- examples/tfengine/generated/org_foundation/live/monitor/forseti/main.tf
- templates/tfengine/components/monitor/forseti/main.tf
https://github.com/terraform-google-modules/terraform-google-cloud-router/releases/tag/v0.2.0
> Update router module version

- cmd/tfengine/README.md
> Fix org_foundation path in README

- examples/tfengine/generated/team/live/example-prod-networks/resources/main.tf
- templates/tfengine/components/resources/compute_networks/main.tf
https://github.com/terraform-google-modules/terraform-google-network
> fix subnet private access typo

- build/gen_check.sh
- cmd/policygen/main.go
- docs/policygen/README.md
- examples/policygen/README.md
- examples/policygen/config.hcl
- internal/policygen/load.go
- internal/policygen/policygen_test.go
- scripts/regen.sh
> support hcl in policygen

- examples/tfengine/generated/team/live/example-prod-apps/resources/main.tf
- examples/tfengine/generated/team/live/example-prod-networks/resources/main.tf
- examples/tfengine/team.hcl
- templates/tfengine/components/resources/bastion_hosts/main.tf
- templates/tfengine/components/resources/compute_instance_templates/main.tf
- templates/tfengine/recipes/resources.hcl
> Add support for compute instance templates and instances

- go.mod
- go.sum
- internal/template/funcmap.go
Useful for generating the current time or expiry dates (via `(Time).AddDate`).
> Add time function and function to add int

- examples/tfengine/generated/team/live/example-prod-apps/resources/main.tf
- examples/tfengine/team.hcl
- templates/tfengine/components/resources/binary_authorization/main.tf
- templates/tfengine/recipes/resources.hcl
> add support for binary authorization

- examples/tfengine/generated/team/live/cicd/terraform.tfvars
- examples/tfengine/generated/team/live/example-prod-apps/project/main.tf
- examples/tfengine/generated/team/live/example-prod-apps/resources/main.tf
- examples/tfengine/generated/team/live/example-prod-data/resources/main.tf
- examples/tfengine/team.hcl
- templates/tfengine/components/resources/pubsub_topics/main.tf
- templates/tfengine/recipes/resources.hcl
> support pubsub

- .gitignore
- build/build-release.sh
- scripts/build.sh
Will use this for releasing the first version. Working on basic release docs too.
> Basic build script

- build/build-binaries.sh
- build/build-include.sh
- build/build-policies.sh
- build/build-templates.sh
This way they can be individually used in release automation.
> Separate build functions

- .github/workflows/release-binaries.yaml
- .github/workflows/release-policies.yaml
- .github/workflows/release-templates.yaml
- build/install-hub.sh
Docs:
* https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-and-managing-workflow-files-and-runs
* https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token
* https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
* https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsrun
* https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
* https://github.com/github/hub#github-actions
> GitHub Actions workflows for release automation

- examples/tfengine/devops.hcl
- examples/tfengine/generated/devops/cicd/README.md
- examples/tfengine/generated/devops/cicd/configs/tf-deletion-check.sh
- examples/tfengine/generated/devops/cicd/configs/tf-plan.yaml
- examples/tfengine/generated/folder_foundation/cicd/README.md
- examples/tfengine/generated/folder_foundation/cicd/configs/tf-deletion-check.sh
- examples/tfengine/generated/folder_foundation/cicd/configs/tf-plan.yaml
- examples/tfengine/generated/org_foundation/cicd/README.md
- examples/tfengine/generated/org_foundation/cicd/configs/tf-deletion-check.sh
- examples/tfengine/generated/org_foundation/cicd/configs/tf-plan.yaml
- examples/tfengine/generated/team/cicd/README.md
- examples/tfengine/generated/team/cicd/configs/tf-deletion-check.sh
- examples/tfengine/generated/team/cicd/configs/tf-plan.yaml
- templates/tfengine/components/cicd/manual/README.md
- templates/tfengine/components/cicd/manual/configs/tf-deletion-check.sh
- templates/tfengine/components/cicd/manual/configs/tf-plan.yaml
This is a breaking change. Existing user of the `tf-deletion-whitelist.txt` needs to rename it to `tf-deletion-allowlist.txt`.
> change to more inclusive language

- docs/tfengine/README.md
I added some updates to the docs for things that slowed me down when running through the installation.
I resubmitted this pull request because I had to use an email that allows me to sign the CLI
> incorporate comments from previous pull request

- examples/tfengine/devops.hcl
- examples/tfengine/folder_foundation.hcl
- examples/tfengine/generated/devops/cicd/main.tf
- examples/tfengine/org_foundation.hcl
- examples/tfengine/team.hcl
- templates/tfengine/components/cicd/manual/main.tf
- templates/tfengine/recipes/devops.hcl
Fixes https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/476
> improve cicd trigger block

- renovate.json
This should get around the need for us to run regen.sh all the time.
> Group all terraform updates together

- build/build-include.sh
> Fix release regex

- renovate.json
This may work better, since it's very direct (group all .tf files).
> Try using paths instead of managers

- docs/tfengine/recipes/resources.md
- examples/tfengine/generated/team/example-prod-secrets/main.tf
- examples/tfengine/team.hcl
- templates/tfengine/components/resources/compute_networks/main.tf
- templates/tfengine/components/resources/secrets/main.tf
- templates/tfengine/recipes/resources.hcl
https://www.terraform.io/docs/providers/google/r/secret_manager_secret.html
> fix secret locations

- internal/pathutil/pathutil.go
- internal/tfengine/tfengine.go
- internal/tfengine/tfengine_test.go
Fixes https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/438
> Supporting outputting individual component files

- .github/workflows/release-latest-binaries.yaml
> Add sleep to latest release

- docs/policygen/README.md
- examples/policygen/config.hcl
- examples/policygen/config.yaml
- examples/policygen/generated/forseti_policies/policies/constraints/organization_12345678/iam_allow_bindings_appengine_appviewer.yaml
- examples/policygen/generated/forseti_policies/policies/constraints/organization_12345678/iam_allow_bindings_bigquery_metadataviewer.yaml
- examples/policygen/generated/forseti_policies/policies/constraints/organization_12345678/iam_allow_bindings_browser.yaml
- examples/policygen/generated/forseti_policies/policies/constraints/organization_12345678/iam_allow_bindings_cloudasset_viewer.yaml
- examples/policygen/generated/forseti_policies/policies/constraints/organization_12345678/iam_allow_bindings_cloudsql_viewer.yaml
- examples/policygen/generated/forseti_policies/policies/constraints/organization_12345678/iam_allow_bindings_compute_networkviewer.yaml
- examples/policygen/generated/forseti_policies/policies/constraints/organization_12345678/iam_allow_bindings_custom_osloginprojectget_6afd.yaml
- examples/policygen/generated/forseti_policies/policies/constraints/organization_12345678/iam_allow_bindings_iam_securityreviewer.yaml
- examples/policygen/generated/forseti_policies/policies/constraints/organization_12345678/iam_allow_bindings_orgpolicy_policyviewer.yaml
- examples/policygen/generated/forseti_policies/policies/constraints/organization_12345678/iam_allow_bindings_servicemanagement_quotaviewer.yaml
- examples/policygen/generated/forseti_policies/policies/constraints/organization_12345678/iam_allow_bindings_serviceusage_serviceusageconsumer.yaml
- examples/policygen/generated/forseti_policies/policies/constraints/organization_12345678/iam_allow_roles.yaml
- examples/policygen/generated/forseti_policies/policies/constraints/overall/bigquery_allow_locations.yaml
- examples/policygen/generated/forseti_policies/policies/constraints/overall/dataproc_allow_locations.yaml
- examples/policygen/generated/forseti_policies/policies/constraints/overall/iam_allow_domains.yaml
- examples/policygen/generated/forseti_policies/policies/constraints/overall/iam_deny_public_access.yaml
- examples/policygen/generated/forseti_policies/policies/constraints/overall/iam_enable_audit_logs.yaml
- examples/policygen/generated/forseti_policies/policies/constraints/overall/network_enable_firewall_logs.yaml
- examples/policygen/generated/forseti_policies/policies/constraints/overall/network_enable_flow_logs.yaml
- examples/policygen/generated/forseti_policies/policies/constraints/overall/sql_allow_locations.yaml
- examples/policygen/generated/forseti_policies/policies/constraints/overall/sql_deny_public_access.yaml
- examples/policygen/generated/forseti_policies/policies/constraints/overall/storage_allow_locations.yaml
- examples/policygen/generated/forseti_policies/policies/constraints/overall/storage_allow_uniform_bucket_access_only.yaml
- internal/policygen/iam.go
- internal/policygen/schema.go
This is a recent update in FCV and follows https://github.com/forseti-security/policy-library/pull/365
> Pluralize policy targets.

- examples/tfengine/generated/team/example-prod-secrets/main.tf
- examples/tfengine/team.hcl
- internal/template/template.go
- templates/tfengine/components/resources/secrets/main.tf
> support secret locations

- cmd/tfengine/main.go
- internal/tfengine/tfengine.go
Fixes https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/544
> Add --templates flag to Engine

- docs/tfengine/schemas/audit.md
- examples/tfengine/folder_foundation.hcl
- examples/tfengine/generated/folder_foundation/audit/main.tf
- templates/tfengine/components/audit/main.tf
- templates/tfengine/recipes/audit.hcl
Fixes https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/606
> support custom log filters

- examples/policygen/generated/forseti_policies/policies/templates/gcp_gke_dashboard_v1.yaml
- internal/tfengine/tfengine.go
> copy even if formatting or license add fails

- docs/tfengine/README.md
The initial caller needs billing admin role to grant CICD SA billing user role.
> Fix billing account permission

- renovate.json
Documentation for Renovate Bot's support for scheduling:
* https://docs.renovatebot.com/noise-reduction/
* https://docs.renovatebot.com/presets-schedule/
* https://docs.renovatebot.com/config-presets/#how-to-use-preset-configs
> Schedule terraform updates to once a month

- docs/tfengine/schemas/project.md
- examples/tfengine/README.md
- examples/tfengine/generated/app/modules/project_apps/main.tf
- examples/tfengine/generated/resources_only/resources/main.tf
- examples/tfengine/generated/team/example-prod-apps/main.tf
- examples/tfengine/resources_only.hcl
- templates/tfengine/components/resources/bastion_hosts/main.tf
- templates/tfengine/components/resources/bigquery_datasets/main.tf
- templates/tfengine/components/resources/binary_authorization/main.tf
- templates/tfengine/components/resources/cloud_sql_instances/main.tf
- templates/tfengine/components/resources/compute_instance_templates/main.tf
- templates/tfengine/components/resources/compute_networks/main.tf
- templates/tfengine/components/resources/compute_routers/main.tf
- templates/tfengine/components/resources/dns_zones/main.tf
- templates/tfengine/components/resources/gke_clusters/main.tf
- templates/tfengine/components/resources/healthcare_datasets/main.tf
- templates/tfengine/components/resources/iam_members/main.tf
- templates/tfengine/components/resources/pubsub_topics/main.tf
- templates/tfengine/components/resources/secrets/main.tf
- templates/tfengine/components/resources/service_accounts/main.tf
- templates/tfengine/components/resources/storage_buckets/main.tf
- templates/tfengine/recipes/audit.hcl
- templates/tfengine/recipes/monitor.hcl
- templates/tfengine/recipes/project.hcl
> support resource only deployment

- docs/tfengine/schemas/cicd.md
- examples/tfengine/devops.hcl
- examples/tfengine/folder_foundation.hcl
- examples/tfengine/generated/devops/cicd/main.tf
- examples/tfengine/generated/folder_foundation/cicd/main.tf
- examples/tfengine/generated/multi_envs/cicd/main.tf
- examples/tfengine/generated/org_foundation/cicd/main.tf
- examples/tfengine/generated/team/cicd/main.tf
- examples/tfengine/multi_envs.hcl
- examples/tfengine/org_foundation.hcl
- examples/tfengine/team.hcl
- templates/tfengine/components/cicd/main.tf
- templates/tfengine/components/cicd/terraform.tfvars
- templates/tfengine/recipes/cicd.hcl
> support adding build editors in cicd

- examples/tfengine/devops.hcl
- examples/tfengine/folder_foundation.hcl
- examples/tfengine/generated/multi_envs/devops/main.tf
- examples/tfengine/multi_envs.hcl
- examples/tfengine/org_foundation.hcl
- examples/tfengine/team.hcl
> allow and add example for using groups in devops recipe

- build/build-include.sh
- cmd/policygen/main.go
- cmd/tfengine/main.go
- cmd/tfimport/main.go
- cmd/version.go
Fixes https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/700
> Show date of build in binaries

- examples/tfengine/folder_foundation.hcl
- examples/tfengine/generated/folder_foundation/monitor/main.tf
- examples/tfengine/generated/org_foundation/monitor/main.tf
- examples/tfengine/org_foundation.hcl
to work around
https://github.com/terraform-google-modules/terraform-google-project-factory/issues/524
and compute API is needed by Forseti anyway
> enable compute API in monitoring project examples

- .github/workflows/release-latest-binaries.yaml
https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/710
> attempt to fix hub path in latest binary release config

- .github/workflows/release-latest-binaries.yaml
https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/710
> always attempt to delete the latest release

- docs/tfengine/schemas/audit.md
- examples/tfengine/folder_foundation.hcl
- examples/tfengine/generated/folder_foundation/audit/main.tf
- examples/tfengine/generated/multi_envs/audit/main.tf
- examples/tfengine/generated/org_foundation/audit/main.tf
- examples/tfengine/multi_envs.hcl
- templates/tfengine/components/audit/main.tf
- templates/tfengine/recipes/audit.hcl
> support user-defined audit logs sink names

- internal/tfimport/tfimport.go
- internal/tfimport/tfimport_test.go
Documentation: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/service_usage_consumer_quota_override#import
> Importer: Add google_service_usage_consumer_quota_override

- docs/tfengine/schemas/devops.md
- examples/tfengine/generated/multi_envs/devops/main.tf
- examples/tfengine/multi_envs.hcl
- templates/tfengine/components/devops/main.tf
- templates/tfengine/recipes/devops.hcl
> add caller as default owner in devops groups if none is specified

- examples/policygen/generated/forseti_policies/policies/templates/gcp_storage_bucket_policy_only_v1.yaml
Due to https://github.com/forseti-security/policy-library/pull/390
> update upstream policy library templates

- templates/tfengine/recipes/audit.hcl
- templates/tfengine/recipes/cicd.hcl
- templates/tfengine/recipes/devops.hcl
- templates/tfengine/recipes/project.hcl
- templates/tfengine/recipes/resources.hcl
Fixes #698
Project ID restriction reference: https://cloud.google.com/resource-manager/docs/creating-managing-projects#before_you_begin
> add pattern restriction for project ID

- examples/tfengine/app.hcl
- examples/tfengine/generated/app/modules/project_apps/main.tf
- examples/tfengine/generated/team/example-prod-apps/main.tf
- examples/tfengine/team.hcl
- templates/tfengine/components/resources/gke_clusters/main.tf
> support deploying GKE cluster with TF 0.13

- examples/tfengine/generated/app/modules/project_apps/main.tf
- examples/tfengine/generated/app/modules/project_data/main.tf
- examples/tfengine/generated/app/modules/project_networks/main.tf
- examples/tfengine/generated/app/modules/project_secrets/main.tf
- examples/tfengine/generated/folder_foundation/audit/main.tf
- examples/tfengine/generated/folder_foundation/example-prod-networks/main.tf
- examples/tfengine/generated/folder_foundation/monitor/main.tf
- examples/tfengine/generated/multi_envs/audit/main.tf
- examples/tfengine/generated/multi_envs/dev/data/main.tf
- examples/tfengine/generated/multi_envs/prod/data/main.tf
- examples/tfengine/generated/org_foundation/audit/main.tf
- examples/tfengine/generated/org_foundation/example-prod-networks/main.tf
- examples/tfengine/generated/org_foundation/monitor/main.tf
- examples/tfengine/generated/team/example-prod-apps/main.tf
- examples/tfengine/generated/team/example-prod-data/main.tf
- examples/tfengine/generated/team/example-prod-networks/main.tf
- examples/tfengine/generated/team/example-prod-secrets/main.tf
- templates/tfengine/components/project/main.tf
> enable grant_services_security_admin_role feature

- docs/tfengine/schemas/cicd.md
- templates/tfengine/components/cicd/main.tf
- templates/tfengine/recipes/cicd.hcl
> support not giving cicd billing user role

- cmd/tfimport/main.go
Fixes https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/788
> Add --verbose flag to tfimport

- cmd/tfimport/main.go
- internal/tfimport/tfimport.go
Fixes https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/781
> Track skipped resources and re-skip on retry

- examples/tfengine/generated/app/envs/shared/cicd/configs/import.sh
- examples/tfengine/generated/devops/cicd/configs/import.sh
- examples/tfengine/generated/folder_foundation/cicd/configs/import.sh
- examples/tfengine/generated/multi_envs/cicd/configs/import.sh
- examples/tfengine/generated/org_foundation/cicd/configs/import.sh
- examples/tfengine/generated/team/cicd/configs/import.sh
- templates/tfengine/components/cicd/configs/import.sh
I'll update the version of tfimport later
> use = in flags in import.sh

- internal/tfimport/tfimport.go
Keep track of succeeded, skipped, and errored imports in the main loop, and report on them at the end of it.
> Importer: Refactor and add final summary of results

- examples/tfengine/generated/app/envs/shared/cicd/configs/import.sh
- examples/tfengine/generated/devops/cicd/configs/import.sh
- examples/tfengine/generated/folder_foundation/cicd/configs/import.sh
- examples/tfengine/generated/multi_envs/cicd/configs/import.sh
- examples/tfengine/generated/org_foundation/cicd/configs/import.sh
- examples/tfengine/generated/team/cicd/configs/import.sh
- templates/tfengine/components/cicd/configs/import.sh
> minor change in usage log of import.sh

- examples/tfengine/generated/devops/groups/main.tf
- examples/tfengine/generated/folder_foundation/audit/main.tf
- examples/tfengine/generated/folder_foundation/example-prod-networks/main.tf
- examples/tfengine/generated/folder_foundation/folders/main.tf
- examples/tfengine/generated/folder_foundation/groups/main.tf
- examples/tfengine/generated/folder_foundation/monitor/main.tf
- examples/tfengine/generated/multi_envs/audit/main.tf
- examples/tfengine/generated/multi_envs/dev/data/main.tf
- examples/tfengine/generated/multi_envs/folders/main.tf
- examples/tfengine/generated/multi_envs/groups/main.tf
- examples/tfengine/generated/multi_envs/prod/data/main.tf
- examples/tfengine/generated/org_foundation/audit/main.tf
- examples/tfengine/generated/org_foundation/example-prod-networks/main.tf
- examples/tfengine/generated/org_foundation/folders/main.tf
- examples/tfengine/generated/org_foundation/groups/main.tf
- examples/tfengine/generated/org_foundation/monitor/main.tf
- examples/tfengine/generated/org_foundation/org_policies/main.tf
- examples/tfengine/generated/org_policies/org_policies/main.tf
- examples/tfengine/generated/resources_only/resources/main.tf
- examples/tfengine/generated/team/groups/main.tf
- examples/tfengine/generated/team/kubernetes/main.tf
- examples/tfengine/generated/team/project_apps/main.tf
- examples/tfengine/generated/team/project_data/main.tf
- examples/tfengine/generated/team/project_networks/main.tf
- examples/tfengine/generated/team/project_secrets/main.tf
- templates/tfengine/components/terraform/main/main.tf
> pin default kubernetes provider version

- examples/tfengine/devops.hcl
- examples/tfengine/folder_foundation.hcl
- examples/tfengine/generated/team/cicd/terraform.tfvars
- examples/tfengine/generated/team/cicd/triggers.tf
- examples/tfengine/generated/team/devops/main.tf
- examples/tfengine/generated/team/groups/main.tf
- examples/tfengine/generated/team/kubernetes/main.tf
- examples/tfengine/generated/team/project_apps/main.tf
- examples/tfengine/generated/team/project_data/main.tf
- examples/tfengine/generated/team/project_networks/main.tf
- examples/tfengine/generated/team/project_secrets/main.tf
- examples/tfengine/modules/foundation.hcl
- examples/tfengine/modules/team.hcl
- examples/tfengine/multi_envs.hcl
- examples/tfengine/org_foundation.hcl
- examples/tfengine/team.hcl
- templates/tfengine/recipes/devops.hcl
https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/763
> fix and cleanup team.hcl example

- examples/tfengine/generated/team/project_apps/main.tf
- examples/tfengine/modules/team.hcl
https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/763
> add an example for account_id reference

- internal/tfimport/tfimport.go
- internal/tfimport/tfimport_test.go
Fixes https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/837
> Importer: Add google_project_iam_audit_config

- docs/tfengine/template_dev.md
https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/763
> add more docs on dependencies

- internal/tfimport/tfimport.go
- internal/tfimport/tfimport_test.go
Fixes https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/836
> Importer: Add google_logging_metric

- docs/tfengine/template_dev.md
- examples/tfengine/modules/foundation.hcl
- examples/tfengine/modules/root.hcl
- examples/tfengine/modules/team.hcl
- examples/tfengine/team.hcl
Fixes https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/767
> add more examples and docs around custom schema and pattern

- docs/tfengine/schemas/resources.md
- examples/tfengine/generated/team/project_apps/main.tf
- examples/tfengine/modules/team.hcl
- go.sum
- templates/tfengine/components/resources/compute_instance_templates/main.tf
- templates/tfengine/recipes/resources.hcl
> support metadata field in compute instance template

- build/presubmit_int.yaml
- build/presubmit_unit.yaml
- docs/tfengine/schemas/resources.md
- examples/tfengine/generated/team/project_apps/main.tf
- examples/tfengine/generated/team/project_data/main.tf
- examples/tfengine/generated/team/project_networks/main.tf
- examples/tfengine/modules/team.hcl
- internal/tfengine/tfengine_test.go
- templates/tfengine/components/resources/cloud_sql_instances/main.tf
- templates/tfengine/recipes/resources.hcl
- tests/tfengine/integration_test.go
Fixes #852
The `integration-tests` build is configured to be only triggered when a repository collaborator or owner comments `/gcbrun`.
> Add Terraform Engine integration tests

- examples/tfengine/generated/devops/cicd/README.md
- examples/tfengine/generated/devops/cicd/configs/run.sh
- examples/tfengine/generated/devops/cicd/configs/tf-apply.yaml
- examples/tfengine/generated/devops/cicd/configs/tf-plan.yaml
- examples/tfengine/generated/devops/cicd/configs/tf-validate.yaml
- examples/tfengine/generated/folder_foundation/cicd/README.md
- examples/tfengine/generated/folder_foundation/cicd/configs/run.sh
- examples/tfengine/generated/folder_foundation/cicd/configs/tf-apply.yaml
- examples/tfengine/generated/folder_foundation/cicd/configs/tf-plan.yaml
- examples/tfengine/generated/folder_foundation/cicd/configs/tf-validate.yaml
- examples/tfengine/generated/multi_envs/cicd/README.md
- examples/tfengine/generated/multi_envs/cicd/configs/run.sh
- examples/tfengine/generated/multi_envs/cicd/configs/tf-apply.yaml
- examples/tfengine/generated/multi_envs/cicd/configs/tf-plan.yaml
- examples/tfengine/generated/multi_envs/cicd/configs/tf-validate.yaml
- examples/tfengine/generated/org_foundation/cicd/README.md
- examples/tfengine/generated/org_foundation/cicd/configs/run.sh
- examples/tfengine/generated/org_foundation/cicd/configs/tf-apply.yaml
- examples/tfengine/generated/org_foundation/cicd/configs/tf-plan.yaml
- examples/tfengine/generated/org_foundation/cicd/configs/tf-validate.yaml
- examples/tfengine/generated/team/cicd/README.md
- examples/tfengine/generated/team/cicd/configs/run.sh
- examples/tfengine/generated/team/cicd/configs/tf-apply.yaml
- examples/tfengine/generated/team/cicd/configs/tf-plan.yaml
- examples/tfengine/generated/team/cicd/configs/tf-validate.yaml
- templates/tfengine/components/cicd/README.md
- templates/tfengine/components/cicd/configs/run.sh
- templates/tfengine/components/cicd/configs/tf-apply.yaml
- templates/tfengine/components/cicd/configs/tf-plan.yaml
- templates/tfengine/components/cicd/configs/tf-validate.yaml
> do not init backend during validate and lock state in plan

- go.mod
- go.sum
> Update module github.com/hashicorp/go-getter to v1.5.4 (#905)

- docs/tfengine/schemas/project.md
- templates/tfengine/recipes/project.hcl
- Update description to field added at #916
> fix: Change project recipe project.api_identities.api description

- docs/tfengine/schemas/project.md
- templates/tfengine/recipes/project.hcl
* fix: Change project recipe project.api_identities.api description
> fix: Change project recipe project.api_identities.api description (#919)

- internal/tfengine/tfengine.go
Fixes: https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/952
> Provide the schema in templates

- docs/tfengine/schemas/iam_members.md
- docs/tfengine/schemas/resources.md
- scripts/generate_schema_docs/main.go
- scripts/generate_schema_docs/schema.go
Fixes https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/960
> Add patternProperties to schema docs

- docs/tfengine/schemas/config.md
- internal/tfengine/config.go
- internal/tfengine/schema.go
- internal/tfengine/tfengine.go
This allows directly passing keys from one recipe to the next.
https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/951
> Add Passthrough support

- internal/template/funcmap.go
- templates/tfengine/components/audit/variables.tf
- templates/tfengine/components/cicd/triggers/apply/variables.tf
- templates/tfengine/components/cicd/triggers/plan/variables.tf
- templates/tfengine/components/cicd/triggers/validate/variables.tf
- templates/tfengine/components/cicd/triggers/variables.tf
- templates/tfengine/components/cicd/variables.tf
- templates/tfengine/components/devops/variables.tf
- templates/tfengine/components/project/variables.tf
- templates/tfengine/recipes/audit.hcl
- templates/tfengine/recipes/cicd.hcl
- templates/tfengine/recipes/devops.hcl
- templates/tfengine/recipes/project.hcl
Implemented `terraformPattern` function to render the correct pattern in the template. The objective is to avoid maintenance of specific fields and make the templates smart enough to render the pattern depending on what's available.
Closes #987
> Apply terraformPattern function

- docs/tfengine/schemas/resources.md
- examples/tfengine/generated/resources_only/resources/main.tf
- examples/tfengine/resources_only.hcl
- templates/tfengine/components/resources/storage_buckets/main.tf
- templates/tfengine/recipes/resources.hcl
Added force_destroy option to storage_buckets resource schema
Closes #973
> Allow specifying force_destroy on storage_bucket resource

- docs/tfengine/schemas/iam_members.md
- templates/tfengine/recipes/iam_members.hcl
> Add additional Terraform configuration in the iam_members.hcl recipe

- examples/policygen/generated/forseti_policies/policies/templates/gcp_allowed_resource_types.yaml
- examples/policygen/generated/forseti_policies/policies/templates/gcp_app_service_versions.yaml
- examples/policygen/generated/forseti_policies/policies/templates/gcp_bigquery_dataset_world_readable_v1.yaml
- examples/policygen/generated/forseti_policies/policies/templates/gcp_dataproc_location_v1.yaml
- examples/policygen/generated/forseti_policies/policies/templates/gcp_gke_master_authorized_networks_enabled_v1.yaml
- examples/policygen/generated/forseti_policies/policies/templates/gcp_restricted_firewall_rules_v1.yaml
- examples/policygen/generated/forseti_policies/policies/templates/gcp_spanner_location_v1.yaml
- examples/policygen/generated/forseti_policies/policies/templates/gcp_storage_bucket_world_readable_v1.yaml
- examples/policygen/generated/forseti_policies/policies/templates/gcp_vpc_sc_ip_range_v1.yaml
- examples/policygen/generated/forseti_policies/policies/templates/legacy/gcp_allowed_resource_types_v1.yaml
The changes are auto-generated by running ./scripts/regen.sh at the root of the repo.
> Pull in latest policy library files.

- docs/tfengine/schemas/cicd.md
- docs/tfengine/schemas/devops.md
- examples/tfengine/generated/devops/cicd/main.tf
- examples/tfengine/generated/devops/devops/main.tf
- examples/tfengine/generated/folder_foundation/cicd/main.tf
- examples/tfengine/generated/folder_foundation/devops/main.tf
- examples/tfengine/generated/multi_envs/cicd/main.tf
- examples/tfengine/generated/multi_envs/devops/main.tf
- examples/tfengine/generated/org_foundation/cicd/main.tf
- examples/tfengine/generated/org_foundation/devops/main.tf
- examples/tfengine/generated/team/cicd/main.tf
- examples/tfengine/generated/team/devops/main.tf
- examples/tfengine/modules/foundation.hcl
- templates/tfengine/components/cicd/main.tf
- templates/tfengine/components/devops/main.tf
- templates/tfengine/components/terraform/main/main.tf
- templates/tfengine/recipes/cicd.hcl
- templates/tfengine/recipes/devops.hcl
> Support terraform_addons in devops and cicd recipes.

- examples/tfengine/generated/devops/cicd/configs/tf-apply.yaml
- examples/tfengine/generated/devops/cicd/configs/tf-plan.yaml
- examples/tfengine/generated/devops/cicd/configs/tf-validate.yaml
- examples/tfengine/generated/folder_foundation/cicd/configs/tf-apply.yaml
- examples/tfengine/generated/folder_foundation/cicd/configs/tf-plan.yaml
- examples/tfengine/generated/folder_foundation/cicd/configs/tf-validate.yaml
- examples/tfengine/generated/multi_envs/cicd/configs/tf-apply.yaml
- examples/tfengine/generated/multi_envs/cicd/configs/tf-plan.yaml
- examples/tfengine/generated/multi_envs/cicd/configs/tf-validate.yaml
- examples/tfengine/generated/org_foundation/cicd/configs/tf-apply.yaml
- examples/tfengine/generated/org_foundation/cicd/configs/tf-plan.yaml
- examples/tfengine/generated/org_foundation/cicd/configs/tf-validate.yaml
- examples/tfengine/generated/team/cicd/configs/tf-apply.yaml
- examples/tfengine/generated/team/cicd/configs/tf-plan.yaml
- examples/tfengine/generated/team/cicd/configs/tf-validate.yaml
- templates/tfengine/components/cicd/configs/tf-apply.yaml
- templates/tfengine/components/cicd/configs/tf-plan.yaml
- templates/tfengine/components/cicd/configs/tf-validate.yaml
Added golang to developer-tools-light https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/1245
> Update docker image version for cloud build triggers

- examples/tfengine/generated/devops/cicd/configs/tf-apply.yaml
- examples/tfengine/generated/devops/cicd/configs/tf-plan.yaml
- examples/tfengine/generated/devops/cicd/configs/tf-validate.yaml
- examples/tfengine/generated/folder_foundation/cicd/configs/tf-apply.yaml
- examples/tfengine/generated/folder_foundation/cicd/configs/tf-plan.yaml
- examples/tfengine/generated/folder_foundation/cicd/configs/tf-validate.yaml
- examples/tfengine/generated/multi_envs/cicd/configs/tf-apply.yaml
- examples/tfengine/generated/multi_envs/cicd/configs/tf-plan.yaml
- examples/tfengine/generated/multi_envs/cicd/configs/tf-validate.yaml
- examples/tfengine/generated/org_foundation/cicd/configs/tf-apply.yaml
- examples/tfengine/generated/org_foundation/cicd/configs/tf-plan.yaml
- examples/tfengine/generated/org_foundation/cicd/configs/tf-validate.yaml
- examples/tfengine/generated/team/cicd/configs/tf-apply.yaml
- examples/tfengine/generated/team/cicd/configs/tf-plan.yaml
- examples/tfengine/generated/team/cicd/configs/tf-validate.yaml
- templates/tfengine/components/cicd/configs/tf-apply.yaml
- templates/tfengine/components/cicd/configs/tf-plan.yaml
- templates/tfengine/components/cicd/configs/tf-validate.yaml
Current version (1.7.1) has some bugs with the terraform version(1.3.0). So, changing the version to 1.6.2 which has terrraform version 1.2.9.
> Update cicd docker image to 1.6.2
