templates/tfengine/components/bootstrap/main.tf
templates/tfengine/components/org/monitor/forseti/main.tf

- terraform provider version should still be pinned when remote backend is disabled
- Set Forseti module to not manage rules

Keep terraform block when remote backend is not enabled.

---

templates/tfengine/components/cicd/configs/tf-deletion-check.sh
templates/tfengine/components/cicd/configs/tf-plan.yaml

The auto-generated tf-deletion-check.yaml file from engine does not
always have execution permission. Use bash as entrypoint is safer.

Use bash as entrypoint to run deletion check script.

---

build/go_check.sh
build/md_check.sh
build/presubmit.yaml

See https://github.com/igorshubovych/markdownlint-cli/issues/90#issuecomment-624266496:
```
The CLI advertises a minimum version of Node 10
```
The gcr.io/cloud-builders/npm container seems to have a `node-10.10.0` tag, but that's static, and `current` is also 10+ and seems to be later than `latest` (unintuitive).

Use later version of Node for md_check

---

internal/terraform/json.go

Remove log message for not found provider config

---

examples/tfengine/full.yaml
examples/tfengine/simple.yaml
templates/tfengine/components/org/audit/main.tf
templates/tfengine/components/org/audit/terraform.tfvars
templates/tfengine/components/org/audit/terragrunt.hcl
templates/tfengine/components/org/audit/variables.tf
templates/tfengine/components/org/monitor/forseti/main.tf
templates/tfengine/components/org/monitor/forseti/terraform.tfvars
templates/tfengine/components/org/monitor/forseti/terragrunt.hcl
templates/tfengine/components/org/monitor/forseti/variables.tf
templates/tfengine/recipes/org/audit.yaml
templates/tfengine/recipes/org/monitor.yaml
templates/tfengine/recipes/org/project.yaml

Change the audit and monitor dir structure to the following:
org/audit/project
org/audit/resources
org/monitor/project
org/monitor/resources
Also support overriding individual resource locations.

simplify audit and monitor

---

examples/tfengine/simple.yaml

GKE isn't used in simple example

rm unused location

---

examples/tfengine/full.yaml
internal/template/funcmap.go
templates/tfengine/components/project/gke_clusters/main.tf
templates/tfengine/components/project/project/main.tf
templates/tfengine/components/project/project/terraform.tfvars
templates/tfengine/components/project/project/variables.tf

NOTE: CFT implements shared VPC inside the project factory module. This is a bit against our curent convention which puts all resources (including all iam) for a project within the project's dir. So in my studies case we had the networks deployment take all service projects as dependencies.
However, project factory instead tries to attach the project to the host project (making the deployment dependency). This approach greatly simplifies the overall configs. Thus, I will use the CFT approach here. In general, we may consider allowing resources like IAM to be defined elsewhere in configs if it greatly simplifies the deployments.
Another con is now someone deploying the apps project also needs permission on the network project to depoy these changes.
There still needs to be dependency to …

Upgrade project factory to new release, add support for shared VPC

---

internal/tfimport/importer/resources_test.go
internal/tfimport/importer/simple_importer.go

This is meant to be used for most resources, where they only require values from the plan.
Resources will be migrated after submitting this change. It should make it much easier to add new resources.

Add SimpleImporter

---

examples/tfengine/full.hcl
examples/tfengine/simple.hcl
templates/tfengine/components/bootstrap/main.tf
templates/tfengine/components/org/audit/main.tf
templates/tfengine/components/org/monitor/forseti/main.tf
templates/tfengine/components/project/bigquery_datasets/main.tf
templates/tfengine/components/project/compute_networks/main.tf
templates/tfengine/components/project/gke_clusters/main.tf
templates/tfengine/components/project/project/main.tf
templates/tfengine/components/project/storage_buckets/main.tf

GCP has regions/locations by service, not individual resource. 
e.g. compute regions (https://cloud.google.com/compute/docs/regions-zones) apply to networks, instances, etc. So we should only create defaults for each service, not resource.

Rename default locations

---

templates/tfengine/recipes/org/project.hcl

This was broken by a bad copy in https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/commit/cc04f89a6055cd8add0007d8d243315d74472618#diff-fe5af5ad0ff5e9996999da5933127196

fix project dirs for audit/monitor

---

cmd/tfimport/README.md
cmd/tfimport/main.go
internal/tfimport/importer/random_integer.go
internal/tfimport/tfimport.go

This list was generated the following way:
1. Run the engine on the full example.
2. Change all backends to "local".
3. Run init to download all modules into .terraform/ folders.
4. Grep for all unique "resource" declarations and filter out ones in `tfimport.go`.
I will add this script to the CI in a follow-up PR.
WANT_LGTM=all

Add all simple resources from the full.hcl example

---

templates/tfengine/components/project/project/main.tf

The CFT module has a weird default of ["compute.googleapis.com"] so if you ever set any api then suddenly compute api tries to get removed which causes a lot of hassles.

always set activate_apis

---

internal/policygen/load.go
internal/policygen/schema.go
internal/tfengine/tfengine.go
templates/tfengine/recipes/org/org_policies.hcl

Fixes #174 
The templating logic that read config and output to appropriate locations will stay in engine or policygen. The most important part is to avoid duplicating the schema.

Merge engine and policygen schema logic for org policies

---

examples/tfengine/full.hcl
templates/tfengine/recipes/project.hcl

Make project directory structure simpler and more consistent with org. Now the user can set the project directory to whatever they like (it doesn't need to be project ID like it was before). Continue using project ID in our examples.

Simplify project recipe

---

examples/tfengine/full.hcl
templates/tfengine/recipes/folder.hcl

We stopped adding a prefix for projects, so do the same for folders.

make folder output path consistent with project

---

.gitattributes

Looking at https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/pull/338, it doesn't seem like the rule quite worked. Adjust it to match all files under the directory as well.

Fix the rule to ignore generated

---

internal/template/template_test.go
internal/terraform/json_test.go
internal/tfimport/importer/resources_test.go

Change all difs to be consistent and show -want +got. This is the more common way and is shown in the exmaple for cmp diff: https://godoc.org/github.com/google/go-cmp/cmp#Diff.
Usually you want to do got before want in test documentation. However for cmp.Diff, it is better to do the opposite as the + will then show exactly the lines you need to add in 'got' and - wil show the lines you need to remove.

make diffs consistent

---

templates/tfengine/recipes/devops.hcl

it is replaced by project.owners

remove legacy project_owners field

---

cmd/tfengine/main.go
docs/policygen/README.md
examples/policygen/config.yaml
examples/tfengine/devops.hcl
internal/policygen/load.go
internal/policygen/policygen.go

also just use a tmp dir for engine remote template cache
Fixes https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/233

support fetch remote policies in policygen

---

build/links_check.sh
build/presubmit.yaml

Only docs folder is checked to not slow down presubmits. Once pure terraform configs are checked in I will go through the whole dir fixing any broken links in components etc.
Fix #325

check links

---

go.sum
internal/template/template.go

No particular reason that this should be an error. Someone could use this to set up a directory structure (envs/, modules/) that they'll populate later.

Create empty output directories with no files

---

examples/tfengine/generated/devops/cicd/configs/run.sh
examples/tfengine/generated/devops/cicd/configs/tf-apply.yaml
examples/tfengine/generated/folder_foundation/cicd/configs/run.sh
examples/tfengine/generated/folder_foundation/cicd/configs/tf-apply.yaml
examples/tfengine/generated/org_foundation/cicd/configs/run.sh
examples/tfengine/generated/org_foundation/cicd/configs/tf-apply.yaml
examples/tfengine/generated/team/cicd/configs/run.sh
examples/tfengine/generated/team/cicd/configs/tf-apply.yaml
templates/tfengine/components/cicd/configs/run.sh
templates/tfengine/components/cicd/configs/tf-apply.yaml

terraform apply -auto-approve does not show the plan, which can make things confusing when something goes wrong with one deployment. Show a plan before apply to be safe.

Multiple actions

---

renovate.json

See this comment: https://github.com/renovatebot/config-help/issues/179#issuecomment-471319331
We were using the default value for ignorePath, which ignores `"**/examples/**"`.

Allow Renovate Bot to update generated .tf files

---

renovate.json

It seems like they didn't work as intended. Now Renovate Bot only updates examples/ but not templates/.
I've asked some questions in https://github.com/renovatebot/config-help/issues/782 and will experiment locally before putting up a new PR.

Revert changes to renovate.json

---

renovate.json

Changes made since last time:
* Target the "regex" manager in the packageRules rule.
* Put `fileMatch` at the top level, where it should be.
* Put `regexManagers` at the top level, where it should be.
* Adjust the regex to handle both deps with submodules (`//`) and without.
The regex was tested against these files via [regex101](https://regex101.com/):
* https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/blob/master/examples/tfengine/generated/team/example-prod-apps/main.tf
* https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/blob/master/templates/tfengine/components/resources/gke_clusters/main.tf

Correct regex match field according to docs

---

examples/tfengine/devops.hcl
examples/tfengine/folder_foundation.hcl
examples/tfengine/generated/devops/cicd/main.tf
examples/tfengine/generated/folder_foundation/cicd/main.tf

us-central1 is not a valid app engine location id

use us-east1 in scheduler example

---

templates/tfengine/components/project/main.tf

Using Go template variables prevents Renovate Bot from seeing  it as a version to update, so it fails on gen_check.sh. See https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/pull/593 for example.

Be explicit with versions for Renovate Bot

---

renovate.json

Adds missing `fileMatch` field to regex manager and removes unnecessary terraform fileMatch.

fix(renovate): add fileMatch to regex manager

---

docs/tfengine/schemas/monitor.md
examples/tfengine/folder_foundation.hcl
examples/tfengine/generated/folder_foundation/example-prod-networks/main.tf
examples/tfengine/generated/folder_foundation/example-prod-networks/outputs.tf
examples/tfengine/generated/folder_foundation/monitor/main.tf
examples/tfengine/generated/org_foundation/cicd/configs/run.sh
examples/tfengine/generated/org_foundation/example-prod-networks/main.tf
examples/tfengine/generated/org_foundation/example-prod-networks/outputs.tf
examples/tfengine/generated/org_foundation/monitor/main.tf
examples/tfengine/org_foundation.hcl
internal/tfengine/integration_test.go
templates/tfengine/components/monitor/forseti/main.tf
templates/tfengine/recipes/monitor.hcl

Don't create network in monitor project, instead use the shared vpc host project to create its network. This is how it should be anyway, but since monitoring was done before networking we didn't migrate it over until now.
Now that the network and forseti instance are created in two different deployments it should work. Note that the initial plan will fail until the network project has been created.

Fix Forseti for 0.13

---

examples/tfengine/app.hcl
examples/tfengine/generated/app/modules/project_apps/main.tf

The current config doesn't work. Setting the service account field requires the user to create the SA. By omitting it, the module will create its own SA for the cluster.

rm compute service account field on gke cluster

---

examples/tfengine/devops.hcl
examples/tfengine/folder_foundation.hcl
examples/tfengine/generated/devops/cicd/main.tf
examples/tfengine/generated/folder_foundation/cicd/main.tf
examples/tfengine/generated/multi_envs/cicd/main.tf
examples/tfengine/generated/org_foundation/cicd/main.tf
examples/tfengine/generated/team/cicd/main.tf
examples/tfengine/multi_envs.hcl
examples/tfengine/org_foundation.hcl
examples/tfengine/team.hcl
templates/tfengine/components/cicd/main.tf
templates/tfengine/recipes/cicd.hcl

The reason is because the app cannot be destroyed after creation. So if
someone first enable scheduler but then disable it. Terraform will throw
errors to destroy it.

always create app engine app in cicd

---

examples/tfengine/generated/devops/devops/main.tf
examples/tfengine/generated/folder_foundation/devops/main.tf
examples/tfengine/generated/multi_envs/devops/main.tf
examples/tfengine/generated/org_foundation/devops/main.tf
examples/tfengine/generated/team/devops/main.tf
templates/tfengine/components/devops/main.tf

It's needed for group creation in devops template or other templates
whose billing project is set to devops project. Always enable it to
simply the code and logic similar to cloud build api is always enabled
in devops.

always enable cloud identity api in devops

---

docs/tfengine/README.md
examples/tfengine/generated/devops/cicd/README.md
examples/tfengine/generated/devops/groups/main.tf
examples/tfengine/generated/folder_foundation/cicd/README.md
examples/tfengine/generated/folder_foundation/groups/main.tf
examples/tfengine/generated/multi_envs/cicd/README.md
examples/tfengine/generated/multi_envs/devops/main.tf
examples/tfengine/generated/multi_envs/groups/main.tf
examples/tfengine/generated/org_foundation/cicd/README.md
examples/tfengine/generated/org_foundation/groups/main.tf
examples/tfengine/generated/team/cicd/README.md
examples/tfengine/generated/team/groups/main.tf
examples/tfengine/multi_envs.hcl
internal/template/funcmap.go
templates/tfengine/components/cicd/README.md
templates/tfengine/components/devops/main.tf
templates/tfengine/components/resources/groups/main.tf

Cloud Identity API will give the display name a default value if not
set. And the next time terraform applies, it will remove that default
name and set to null, which is not as desirable. So we give the same
default display name to the groups.

improve groups doc and display name setting

---

internal/tfimport/tfimport.go

Terraform may be sandboxed or running on a system that can't write to /tmp.
Also print not importable files in dry-run mode.

Use input dir for temp plan file in import

---

docs/tfengine/schemas/devops.md
examples/tfengine/generated/multi_envs/devops/main.tf
examples/tfengine/multi_envs.hcl
templates/tfengine/components/devops/main.tf
templates/tfengine/recipes/devops.hcl

Reverts GoogleCloudPlatform/healthcare-data-protection-suite#727
It has an issue. Because the caller is dynamically calculated, whoever tries to redeploy the `devops` recipe (another user, CICD service account) will cause the removal of previous owner from the group and add itself to the group, which is not desirable. Reverting for now.

Revert "add caller as default owner in devops groups if none is specified"

---

docs/tfengine/schemas/resources.md
examples/tfengine/generated/app/modules/project_apps/main.tf
examples/tfengine/generated/team/example-prod-apps/main.tf
templates/tfengine/components/resources/gke_clusters/main.tf
templates/tfengine/recipes/resources.hcl

It's nice to have for microservices. Does not need to be on by default
in all cases. https://cloud.google.com/istio/docs/istio-on-gke/overview
Also see [Should I use Istio on GKE?](https://cloud.google.com/istio/docs/istio-on-gke/overview#should_i_use). "Due to these limitations and the product's beta status, customers should not use this add-on in production. Anthos Service Mesh or open source Istio are better options for production workloads."

make istio in gke configurable

---

examples/tfengine/generated/app/modules/project_apps/main.tf
examples/tfengine/generated/app/modules/project_data/main.tf
examples/tfengine/generated/folder_foundation/monitor/main.tf
examples/tfengine/generated/org_foundation/monitor/main.tf
examples/tfengine/generated/team/example-prod-apps/main.tf
examples/tfengine/generated/team/example-prod-data/main.tf
templates/tfengine/components/project/main.tf

Fix #697 
There should actually be no recreation needed because both PF and the service project module have the same module resources and names.

only use base project factory module

---

internal/tfimport/tfimport.go

This way there's a clearer message logged in all cases, not just at the end. Useful when for any reason a long-running import freezes and you can see more information up to that point.

Add more logging to tfimport

---

examples/tfengine/generated/app/modules/project_data/main.tf
examples/tfengine/generated/resources_only/resources/main.tf
examples/tfengine/generated/team/project_data/main.tf
templates/tfengine/components/resources/healthcare_datasets/main.tf

google provider v3.54.0 has a critical fix related to creating dataset, need to
pin to healthcare module that enforces that.

upgrade healthcare module to enforce provider version constraint

---

docs/tfengine/schemas/devops.md
docs/tfengine/schemas/resources.md
examples/tfengine/folder_foundation.hcl
examples/tfengine/generated/folder_foundation/groups/main.tf
examples/tfengine/generated/multi_envs/groups/main.tf
examples/tfengine/generated/org_foundation/groups/main.tf
examples/tfengine/multi_envs.hcl
examples/tfengine/org_foundation.hcl
templates/tfengine/recipes/devops.hcl
templates/tfengine/recipes/resources.hcl

This is aligned with documentation in docs/tfengine/README.md. Enforce
it in templates as well.
Underlying issues: https://github.com/terraform-google-modules/terraform-google-group#limitations

restrict members and managers from being specified for groups

---

examples/tfengine/generated/multi_envs/devops/main.tf
templates/tfengine/components/devops/main.tf

The group is not ready for IAM bindings right after the
group resource is deployed.

add a sleep between group creation and IAM bindings

---

examples/tfengine/generated/app/modules/project_data/main.tf
examples/tfengine/generated/resources_only/resources/main.tf
examples/tfengine/generated/team/project_data/main.tf
templates/tfengine/components/resources/healthcare_datasets/main.tf

The current behavior is healthcare module resources will start being
created once the project itself is created and project ID is availale.
This can cause race condition between other resources such as api
identities and fhir store. FHIR store creation should wait for
healthcare api identity permission granting to finish, which is done as
part of the project factory module.
Sample error message is:
Error: Error creating FhirStore: googleapi: Error 403: failed to verify
dataset (projectID:..., datasetID:...),
please add the required bigquery.dataEditor and bigquery.jobUser roles
to your project's service account

make healthcare resources explicitly depend on project module to finish

---

internal/tfimport/tfimport.go

The terraform commands in that function are already running in the InputDir, so we don't need to specify the full path. Seems to not work sometimes.
Fixes #780

Use basename for plan file

---

build/build-include.sh

This lets them run in the Alpine-based containers used in the CI/CD templates.

Build binaries statically

---

cmd/tfimport/main.go
internal/tfimport/tfimport.go

These will be logged by the runner when using the --verbose flag.
Fixes https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/788

Importer: Don't manually log error messages

---

cmd/tfimport/main.go
internal/tfimport/tfimport.go

Take into account verbosity when printing error summary at the end. Also, show errors when some resources were skipped, this was previously wrong.

Change error messages based on verbosity and show errs even with skipped resources

---

examples/tfengine/generated/devops/devops/main.tf
examples/tfengine/generated/devops/groups/main.tf
examples/tfengine/generated/folder_foundation/audit/main.tf
examples/tfengine/generated/folder_foundation/devops/main.tf
examples/tfengine/generated/folder_foundation/example-prod-networks/main.tf
examples/tfengine/generated/folder_foundation/groups/main.tf
examples/tfengine/generated/folder_foundation/monitor/main.tf
examples/tfengine/generated/multi_envs/audit/main.tf
examples/tfengine/generated/multi_envs/dev/data/main.tf
examples/tfengine/generated/multi_envs/devops/main.tf
examples/tfengine/generated/multi_envs/groups/main.tf
examples/tfengine/generated/multi_envs/prod/data/main.tf
examples/tfengine/generated/org_foundation/audit/main.tf
examples/tfengine/generated/org_foundation/devops/main.tf
examples/tfengine/generated/org_foundation/example-prod-networks/main.tf
examples/tfengine/generated/org_foundation/groups/main.tf
examples/tfengine/generated/org_foundation/monitor/main.tf
examples/tfengine/generated/resources_only/resources/main.tf
examples/tfengine/generated/team/devops/main.tf
examples/tfengine/generated/team/groups/main.tf
examples/tfengine/generated/team/project_apps/main.tf
examples/tfengine/generated/team/project_data/main.tf
examples/tfengine/generated/team/project_networks/main.tf
examples/tfengine/generated/team/project_secrets/main.tf
templates/tfengine/components/devops/main.tf
templates/tfengine/components/project/main.tf

To include fix "Additional roles should only granted for Shared VPC when attaching to a service project (https://github.com/terraform-google-modules/terraform-google-project-factory/pull/542) (99093de)"

upgrade project factory module to 10.1.1

---

docs/tfengine/schemas/cicd.md
examples/tfengine/generated/multi_envs/cicd/triggers.tf
examples/tfengine/multi_envs.hcl
templates/tfengine/components/cicd/main.tf
templates/tfengine/recipes/cicd.hcl

Cloud Source Repositories does not support code review or presubmit runs. If we set both plan and apply to run at the same time, they will conflict when trying to acquire the lock and may error out.
To get around this, set only auto-apply for non-prod envs, and only plan for the prod env.

Don't run both plan and apply for CSR

---

README.md

Only adding version badge for binaries for now. I didn't find a way to
filter tags / releases by prefix so I can include badge for templates
and policies as well.

turn release status to stable versions

---

examples/tfengine/generated/devops/cicd/README.md
examples/tfengine/generated/devops/cicd/configs/tf-apply.yaml
examples/tfengine/generated/devops/cicd/configs/tf-plan.yaml
examples/tfengine/generated/devops/cicd/configs/tf-validate.yaml
examples/tfengine/generated/folder_foundation/cicd/README.md
examples/tfengine/generated/folder_foundation/cicd/configs/tf-apply.yaml
examples/tfengine/generated/folder_foundation/cicd/configs/tf-plan.yaml
examples/tfengine/generated/folder_foundation/cicd/configs/tf-validate.yaml
examples/tfengine/generated/multi_envs/cicd/README.md
examples/tfengine/generated/multi_envs/cicd/configs/tf-apply.yaml
examples/tfengine/generated/multi_envs/cicd/configs/tf-plan.yaml
examples/tfengine/generated/multi_envs/cicd/configs/tf-validate.yaml
examples/tfengine/generated/org_foundation/cicd/README.md
examples/tfengine/generated/org_foundation/cicd/configs/tf-apply.yaml
examples/tfengine/generated/org_foundation/cicd/configs/tf-plan.yaml
examples/tfengine/generated/org_foundation/cicd/configs/tf-validate.yaml
examples/tfengine/generated/team/cicd/README.md
examples/tfengine/generated/team/cicd/configs/tf-apply.yaml
examples/tfengine/generated/team/cicd/configs/tf-plan.yaml
examples/tfengine/generated/team/cicd/configs/tf-validate.yaml
templates/tfengine/components/cicd/README.md
templates/tfengine/components/cicd/configs/tf-apply.yaml
templates/tfengine/components/cicd/configs/tf-plan.yaml
templates/tfengine/components/cicd/configs/tf-validate.yaml

The container base is switched in
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/943.
The original one has 72 vulnerabilities reported by GCR. The new one has
zero.

Change CICD container to a more secure one.

---

examples/tfengine/generated/devops/devops/variables.tf
examples/tfengine/generated/folder_foundation/devops/variables.tf
examples/tfengine/generated/multi_envs/devops/variables.tf
examples/tfengine/generated/org_foundation/devops/variables.tf
examples/tfengine/generated/team/devops/variables.tf
templates/tfengine/components/devops/variables.tf

- Remove TODO for testing agains private catalog
Notes: this is how private catalog handles complex data structures

chore: Remove private catalog testing TODO

---

renovate.json

Reverts GoogleCloudPlatform/healthcare-data-protection-suite#925
The change starts breaking the pre-set schedule and the renovate PR no longer groups modules together.

Revert "Change Renovate config to only update modules."

---

templates/tfengine/components/audit/terraform.tfvars
templates/tfengine/components/audit/variables.tf
templates/tfengine/components/cicd/main.tf
templates/tfengine/components/cicd/terraform.tfvars
templates/tfengine/components/cicd/triggers/apply/main.tf
templates/tfengine/components/cicd/triggers/apply/variables.tf
templates/tfengine/components/cicd/triggers/main.tf
templates/tfengine/components/cicd/triggers/plan/main.tf
templates/tfengine/components/cicd/triggers/plan/variables.tf
templates/tfengine/components/cicd/triggers/validate/main.tf
templates/tfengine/components/cicd/triggers/validate/variables.tf
templates/tfengine/components/cicd/triggers/variables.tf
templates/tfengine/components/cicd/variables.tf
templates/tfengine/components/devops/main.tf
templates/tfengine/components/devops/terraform.tfvars
templates/tfengine/components/devops/variables.tf
templates/tfengine/components/iam_members/terraform.tfvars
templates/tfengine/components/iam_members/variables.tf
templates/tfengine/components/org_policies/terraform.tfvars
templates/tfengine/components/org_policies/variables.tf
templates/tfengine/components/terraform/main/main.tf

With the merging of #983, #980 has now compatibility problems regarding the merge of the `.tfvars` from `audit` and `project` components.
One of the main issues was the duplication of the license block due to inconsistent use of it across previous changes. This PR sets every license template to the same format to avoid duplication.

Blueprints use same policy template

---

docs/tfengine/schemas/audit.md
examples/tfengine/generated/folder_foundation/audit/main.tf
examples/tfengine/generated/folder_foundation/audit/terraform.tfvars
examples/tfengine/generated/folder_foundation/audit/variables.tf
examples/tfengine/generated/multi_envs/audit/main.tf
examples/tfengine/generated/multi_envs/audit/terraform.tfvars
examples/tfengine/generated/multi_envs/audit/variables.tf
examples/tfengine/generated/org_foundation/audit/main.tf
examples/tfengine/generated/org_foundation/audit/terraform.tfvars
examples/tfengine/generated/org_foundation/audit/variables.tf
templates/tfengine/components/audit/main.tf
templates/tfengine/components/audit/terraform.tfvars
templates/tfengine/components/audit/variables.tf
templates/tfengine/recipes/audit.hcl

Removed the reference that `audit` recipe is doing to the `project` recipe. This will avoid future duplication of variables at `variables.tf` and `terraform.tfvars`

Remove project recipe reference in audit recipe

---

examples/tfengine/generated/devops/cicd/triggers.tf
examples/tfengine/generated/folder_foundation/cicd/triggers.tf
examples/tfengine/generated/multi_envs/cicd/triggers.tf
examples/tfengine/generated/org_foundation/cicd/triggers.tf
examples/tfengine/generated/team/cicd/triggers.tf
templates/tfengine/components/cicd/triggers.tf

Cloud Build Trigger API is in GA:
https://cloud.google.com/build/docs/api/reference/rest/v1/projects.triggers/create?hl=en_US
(note the v1 label).
Fixes #998

Use GA provider for cloud build triggers.

---

internal/tfengine/tfengine.go
templates/tfengine/recipes/project.hcl

Also removed the error checking, it doesn't work here because one of the fields is optional and isn't always provided. It might be simpler this way and to just let the schema in the child recipe set certain fields as required or not.
Fixes https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/951

Add passthrough to the project recipe

---

examples/tfengine/generated/devops/cicd/configs/tf-deletion-check.sh
examples/tfengine/generated/folder_foundation/cicd/configs/tf-deletion-check.sh
examples/tfengine/generated/multi_envs/cicd/configs/tf-deletion-check.sh
examples/tfengine/generated/org_foundation/cicd/configs/tf-deletion-check.sh
examples/tfengine/generated/team/cicd/configs/tf-deletion-check.sh
templates/tfengine/components/cicd/configs/tf-deletion-check.sh

Sometimes this check fails with "parse error: Invalid numeric literal at line 1, column 2". This looks like it's coming from jq failing to parse the output of terraform show, so log that output separately for debugging.

Add more logging to the deletion check

---

.github/workflows/release-binaries.yaml
RELEASING.md
build/changelog_binaries.sh

Opening this PR for discussion/consideration. This is naive and simple, but is still useful as it shows exactly what went into each binaries release and saves having to run `git log` to confirm that a release contains a specific feature.

Add simple commit log to the binaries release

---

internal/terraform/json.go

I no longer remember what this was supposed to mean, and either way it shouldn't be assigned to me directly; if someone can clarify the missing functionality here, it should be `TODO(<issue #>)`.

Remove TODO(mpetkov)

---

.gitignore
docs/tfengine/schemas/resources.md
examples/tfengine/generated/team/project_data/hl7_config_schema.json
examples/tfengine/generated/team/project_data/main.tf
examples/tfengine/generated/team/project_data/schema.json
examples/tfengine/modules/schema/hl7_config_schema.json
examples/tfengine/modules/team.hcl
templates/tfengine/components/resources/healthcare_datasets/main.tf
templates/tfengine/recipes/resources.hcl

Deployed the change in HDE instance for testing.
instance prefix : test-dpt1
Verified that the parser config through schema_file has been applied to hl7 store successfully.
https://screenshot.googleplex.com/8NJfhrimp44YaKB.png

Support reading hl7v2 parser config from file.

---

examples/tfengine/generated/devops/devops/main.tf
examples/tfengine/generated/devops/groups/main.tf
examples/tfengine/generated/folder_foundation/audit/main.tf
examples/tfengine/generated/folder_foundation/devops/main.tf
examples/tfengine/generated/folder_foundation/example-prod-networks/main.tf
examples/tfengine/generated/folder_foundation/groups/main.tf
examples/tfengine/generated/gke_cluster/gke_cluster/cluster/main.tf
examples/tfengine/generated/gke_cluster/gke_cluster/kubernetes/main.tf
examples/tfengine/generated/gke_cluster/gke_cluster/networks/main.tf
examples/tfengine/generated/multi_envs/audit/main.tf
examples/tfengine/generated/multi_envs/dev/data/main.tf
examples/tfengine/generated/multi_envs/devops/main.tf
examples/tfengine/generated/multi_envs/groups/main.tf
examples/tfengine/generated/multi_envs/prod/data/main.tf
examples/tfengine/generated/org_foundation/audit/main.tf
examples/tfengine/generated/org_foundation/devops/main.tf
examples/tfengine/generated/org_foundation/example-prod-networks/main.tf
examples/tfengine/generated/org_foundation/groups/main.tf
examples/tfengine/generated/resources_only/resources/main.tf
examples/tfengine/generated/team/devops/main.tf
examples/tfengine/generated/team/groups/main.tf
examples/tfengine/generated/team/kubernetes/main.tf
examples/tfengine/generated/team/project_apps/main.tf
examples/tfengine/generated/team/project_data/main.tf
examples/tfengine/generated/team/project_networks/main.tf
examples/tfengine/generated/team/project_secrets/main.tf
templates/tfengine/components/devops/main.tf
templates/tfengine/components/project/main.tf

The old version (11.1.1) [did not allow](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/v11.1.1/modules/project_services/versions.tf#L22) provider versions 4.0 or higher.

Upgrade project-factory version so we can use 4.x provider versions.

---

go.mod
go.sum
internal/fileutil/fileutil.go

go-getter/v2 has several security fixes:
* CVE-2022-30323 - HashiCorp go-getter through 2.0.2 does not safely perform downloads
* CVE-2022-26945 - HashiCorp go-getter before 2.0.2 allows Command Injection
* CVE-2022-29810 - HashiCorp go-getter before 1.5.11 does not redact an SSH key from a URL query parameter

Update go-getter to v2

---

build/md_check.sh
docs/tfengine/schemas/cicd.md
examples/tfengine/generated/devops/cicd/main.tf
examples/tfengine/generated/devops/cicd/triggers.tf
examples/tfengine/generated/folder_foundation/cicd/main.tf
examples/tfengine/generated/folder_foundation/cicd/triggers.tf
examples/tfengine/generated/multi_envs/cicd/main.tf
examples/tfengine/generated/org_foundation/cicd/main.tf
examples/tfengine/generated/team/cicd/main.tf
templates/tfengine/components/cicd/main.tf
templates/tfengine/components/cicd/triggers.tf
templates/tfengine/recipes/cicd.hcl

Cloud Scheduler jobs for HTTP or Pub/Sub Targets can be deployed in multiple GCP Regions around the world and no longer require that an App Engine application be deployed.
Pin markdownlint-cli to version 0.31.1 to disable rule MD052, which is breaking presubmit_unit tests.
Release note: https://cloud.google.com/scheduler/docs/release-notes#February_11_2022

Remove Cloud Scheduler AppEngine Dependency app

---

examples/tfengine/generated/devops/cicd/configs/tf-apply.yaml
examples/tfengine/generated/devops/cicd/configs/tf-plan.yaml
examples/tfengine/generated/devops/cicd/configs/tf-validate.yaml
examples/tfengine/generated/folder_foundation/cicd/configs/tf-apply.yaml
examples/tfengine/generated/folder_foundation/cicd/configs/tf-plan.yaml
examples/tfengine/generated/folder_foundation/cicd/configs/tf-validate.yaml
examples/tfengine/generated/multi_envs/cicd/configs/tf-apply.yaml
examples/tfengine/generated/multi_envs/cicd/configs/tf-plan.yaml
examples/tfengine/generated/multi_envs/cicd/configs/tf-validate.yaml
examples/tfengine/generated/org_foundation/cicd/configs/tf-apply.yaml
examples/tfengine/generated/org_foundation/cicd/configs/tf-plan.yaml
examples/tfengine/generated/org_foundation/cicd/configs/tf-validate.yaml
examples/tfengine/generated/team/cicd/configs/tf-apply.yaml
examples/tfengine/generated/team/cicd/configs/tf-plan.yaml
examples/tfengine/generated/team/cicd/configs/tf-validate.yaml
templates/tfengine/components/cicd/configs/tf-apply.yaml
templates/tfengine/components/cicd/configs/tf-plan.yaml
templates/tfengine/components/cicd/configs/tf-validate.yaml

Updated developer-tools-light to 1.7.1 which has updated the base image to 3.16.2
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/1259

Update docker image for cloud build triggers

---

examples/tfengine/generated/devops/cicd/configs/tf-apply.yaml
examples/tfengine/generated/devops/cicd/configs/tf-plan.yaml
examples/tfengine/generated/devops/cicd/configs/tf-validate.yaml
examples/tfengine/generated/folder_foundation/cicd/configs/tf-apply.yaml
examples/tfengine/generated/folder_foundation/cicd/configs/tf-plan.yaml
examples/tfengine/generated/folder_foundation/cicd/configs/tf-validate.yaml
examples/tfengine/generated/multi_envs/cicd/configs/tf-apply.yaml
examples/tfengine/generated/multi_envs/cicd/configs/tf-plan.yaml
examples/tfengine/generated/multi_envs/cicd/configs/tf-validate.yaml
examples/tfengine/generated/org_foundation/cicd/configs/tf-apply.yaml
examples/tfengine/generated/org_foundation/cicd/configs/tf-plan.yaml
examples/tfengine/generated/org_foundation/cicd/configs/tf-validate.yaml
examples/tfengine/generated/resources_only/resources/main.tf
examples/tfengine/generated/team/cicd/configs/tf-apply.yaml
examples/tfengine/generated/team/cicd/configs/tf-plan.yaml
examples/tfengine/generated/team/cicd/configs/tf-validate.yaml
examples/tfengine/generated/team/project_data/main.tf
templates/tfengine/components/cicd/configs/tf-apply.yaml
templates/tfengine/components/cicd/configs/tf-plan.yaml
templates/tfengine/components/cicd/configs/tf-validate.yaml
templates/tfengine/components/resources/bigquery_datasets/main.tf
templates/tfengine/components/resources/pubsub_topics/main.tf

Update cloud build container image, pubsub module, and bigquery module
About:
- Update cloud build container image to include Terraform 1.10.5
- Update terraform bigquery module to 7.0.0
- Update terraform pubsub module to 6.0

Update cloud build container image, pubsub module, and bigquery module
